name: "Deploy Node Application"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build . -t shehanapareeth/ecommerce-react-frontend 
      - name: Publish Image to docker hub
        run: docker push shehanapareeth/ecommerce-react-frontend :latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker  hub
        run: docker pull shehanapareeth/ecommerce-react-frontend 
      - name: Delete Old Container
        run: docker rm -f reactjs-app-container 
      - name: Run Docker Container
        run: docker run  -p 3000:80 --name reactjs-app-container shehanapareeth/ecommerce-react-frontend 
