name: "Deploy Node Application"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t shehanapareeth/ecommerce-react-frontend  . 
      - name: Publish Image to docker hub
        run: docker push shehanapareeth/ecommerce-react-frontend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker  hub
        run: docker pull shehanapareeth/ecommerce-react-frontend:latest
      - name: Remove existing container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container  -e REACT_APP_BASE_URL='${{ secrets.REACT_APP_BASE_URL }}' shehanapareeth/ecommerce-react-frontend 
      
